#! /bin/bash

# mac ssettings
. ~/dotfiles/other/mac_settings.sh

#install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

rcup -v
(cd ~/dotfiles && brew bundle)


