#! /bin/bash

#install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

rcup -v
(cd ~/.dotfiles && brew bundle)

# install asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.2
