#!/usr/bin/env dash

unwip() {
  if [[ "$(git log -1 --pretty=%B)" = "wip" ]]; then
    git reset head^
  fi
}

mcd () {
  mkdir -pv $1
  cd $1
}

# fh - repeat history
fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac --height 25% --reverse | sed 's/ *[0-9]* *//')
}

# tm - create new tmux session, or switch to existing one. Works from within tmux too. (@bag-man)
# `tm` will allow you to select your tmux session via fzf.
# `tm irc` will attach to the irc session (if it exists), else it will create it.
tm() {
  [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
  if [ $1 ]; then
    tmux $change -t "$1" 2>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1"); return
  fi
  session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0 --height 20% --reverse) &&
    tmux $change -t "$session" || echo "No sessions found."
}

# fbr - checkout git branch
fbr() {
  local branches branch cmd="vv"

  while getopts "a" OPTION
  do
    case $OPTION in
      a) cmd="vva" ;;
    esac
  done

  branches=$(git branch -$cmd) &&
  branch=$(echo "$branches" | fzf +m --height 25% --reverse) &&
  # git checkout $(echo "$branch" | awk '{print $1}' | sed "s/.* //")
  git checkout $(echo "$branch" | awk '{print $1}' | awk -F "/" '{print $NF}' | sed "s/.* //")
}

# fd - cd to selected directory
fdir() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m --height 25% --reverse) &&
  cd "$dir"
}

# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index \
      --preview 'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1; }; f {}' \
      --bind=ctrl-s:toggle-sort \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}


