
# export PS1="\\w\$(__git_ps1 '(%s)') \$ "

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\] \[\033[33;1m\]\w\[\033[m\] \$(git branch 2>/dev/null | grep '^*' | colrm 1 2) \$  \n❯ "

bind "TAB:menu-complete"
bind "set show-all-if-ambiguous on"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f ~/dotfiles/bash/sensible.bash ]; then
   source ~/dotfiles/bash/sensible.bash
fi
